### ISSUE TITLE
未能检测到Hiper核心

### ISSUE THREAD

**Issue by Souiken** [KormiMeiko/HiperDeleteTool#1]
如题
![image](https://user-images.githubusercontent.com/88724486/209551286-735eb5e7-9ece-4a84-88ef-7c7c513bbce7.png)

**Comment by KormiMeiko** [comment]
也许某人换核心名称了吧，过段时间瞅瞅

**Comment by KormiMeiko** [comment]
> 如题 ![image](https://user-images.githubusercontent.com/88724486/209551286-735eb5e7-9ece-4a84-88ef-7c7c513bbce7.png)

更新了0.2版本，增加了对U1的检测。
该版本可以帮助你解决问题。
